import type { Metadata } from "next";
import Navbar from "../ui/navbar";
import { Footer } from "../ui/Footer";
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <div>
    <Navbar/>
 {children}
 <Footer/>
   </div>
)}
